source 'http://git.oschina.net/akuandev/Specs.git' 
pod 'MJRefresh', '~> 2.4.10'
pod 'AFNetworking', '~> 2.6.0'
pod 'pop', '~> 1.0.8'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'UMengSocial', '~> 4.2.3'
pod 'FMDB', '~> 2.5'
